# Generated by Django 4.2.23 on 2025-06-19 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("date_planted", models.DateField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="tree_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("Watering", "Watering"),
                            ("Fertilizing", "Fertilizing"),
                            ("Pest Control", "Pest Control"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="trees.tree",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("health_status", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_logs",
                        to="trees.tree",
                    ),
                ),
            ],
        ),
    ]
