# Generated by Django 4.2.23 on 2025-06-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthlog",
            name="death_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthlog",
            name="is_dead",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tree",
            name="death_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tree",
            name="is_dead",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tree",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tree",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tree",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
