# Generated by Django 4.2.23 on 2025-06-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0003_alter_tree_location_alter_tree_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tree",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tree",
            name="division",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tree",
            name="other_location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
