# Generated by Django 4.2.23 on 2025-06-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0006_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("love", "Love"),
                    ("wow", "Wow"),
                    ("sad", "Sad"),
                ],
                max_length=20,
            ),
        ),
    ]
